.TH "admin-freemem" "1" "Simple-Admin 1.1" "" "Simple-Admin 1.1"
.\" -----------------------------------------------------------------
.\" * disable hyphenation
.nh
.\" * disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.SH "NAME"
admin-freemem -- cleans file system cache (if possible) to recover memory
.SH "SYNOPSIS"
.sp
.nf
\fBadmin-freemem\fR
.fi
.sp
.SH "DESCRIPTION"
.sp
Forces a file system sync followed by writing \fB1\fR to the
\fB/proc/sys/vm/drop_caches\fR file. This results in the Linux kernel cleaning
its file system caches and making that memory available for other uses.

Using \fBadmin-freemem\fR may degrade performance for some applications, since
files must be re-read from the file system. Clearing the file system cache may
also be beneficial if recent large file reads will not be re-used.
.sp
.SH "SEE ALSO"
.sp
\fBproc\fR(5)
