.TH "simple-uptodate" "1" "Simple-Admin" "" "Simple-Admin"
.\" -----------------------------------------------------------------
.\" * disable hyphenation
.nh
.\" * disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.SH "NAME"
simple-uptodate -- checks for and optionally installs system (security) updates
.SH "SYNOPSIS"
.sp
.nf
\fBsimple-uptodate\fR [options]
.fi
.sp
.SH "DESCRIPTION"
.sp
Synchronizes the package index with \fBapt-get update\fR and then runs an
\fBaptitude\fR search for updates. The search can optionally be filtered to
only include security-related updates.

When \fB--autoinstall\fR is specified, the packages found are also updated
with \fBaptitude safe-upgrade\fR.

If no updates are available, no output is printed.
.sp
.SH "OPTIONS"
.sp
-\fBa\fR, --\fBautoinstall\fR
.RS 4
Automatically install updates found.
.RE

-\fBs\fR, --\fBsecurity\fR
.RS 4
Only check for security updates.
.RE

-\fBm\fR, --\fBmail\fR
.RS 4
Mail \fBroot@localhost\fR instead of printing results to standard output.
.RE
.sp
.SH "SEE ALSO"
.sp
\fBapt-get\fR(8),
\fBaptitude\fR(8)
