.TH "simple-backup-files" "1" "Simple-Admin" "" "Simple-Admin"
.\" -----------------------------------------------------------------
.\" * disable hyphenation
.nh
.\" * disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.SH "NAME"
simple-backup-files -- performs a file system backup for configured directories
.SH "SYNOPSIS"
.sp
.nf
\fBsimple-backup-files\fR [-\fBv\fR]
.fi
.sp
.SH "DESCRIPTION"
.sp
Performs a file system backup with \fBrsync\fR of the directories listed in
\fB/etc/simple-backup-files.conf\fR. All files will be recursively copied
to the \fB/backup/\fIhostname\fB/files/latest\fR directory with timestamps
and permissions intact.

Files removed or modified since the last backup will be moved to a new
\fB/backup/\fIhostname\fB/files/\fItimestamp\fR directory. Additional
timestamped directories for the day and month are also created and updated
with these modifications.

The monthly backup directories are kept indefinitely, daily backups are
preserved for 14 days, and any other timestamped backup directory is
preserved for 48 hours. In order to save space, identical files are hard
linked between the timestamped backup directories (if possible).

The backup can be run as frequently as every minute, but should probably be
run once per day to keep disk usage down.
.sp
.SH "OPTIONS"
.sp
-\fBv\fR
.RS 4
Print verbose output.
.RE
.sp
.SH "CONFIGURATION"
.sp
The backup is configured in \fB/etc/simple-backup-files.conf\fR with one line
per directory. Comment or blank lines are ignored. Each line contains a
directory path and an optional number of retention days:
.sp
.nf
    /etc
    /home
    /root
    /var/log   5
.fi
.sp
The optional retention days specifies the maximum number of days to keep the
files from that directory. This value only reduces the default file retention
(as specified above).
.sp
.SH "FILES"
.sp
.B /etc/simple-backup-files.conf
.RS 4
Backup configuration file with one line per directory.
.RE

.B /backup
.RS 4
Backup directory with subdirectories per hostname.
.RE
.sp
.SH "SEE ALSO"
.sp
\fBsimple-backup-search\fR(1),
\fBsimple-backup-status\fR(1),
\fBrsync\fR(1),
<http://www.simple-admin.org/>
